### ISSUE TITLE
[Request] License Clarification

### ISSUE THREAD

**Issue by fallaciousreasoning** [slawomirkolodziej/figma-api-exporter#5]
Hey, thanks for the great library! I started playing around with it for an icon exporter I'm working on at @brave but I just realised you don't have a license on the project.

I was wondering if you'd be able to add an open source one?

(also, I have a PR for batching (#4), if you're accepting contributions)

FWIW, most of the stuff at Brave is using the MIT or Mozilla Public License

**Comment by slawomirkolodziej** [comment]
hey!
I haven't worked on this project for a while. I invited you to be a collaborator. I hope you will be able to make all the changes you need and that this package will serve you well in your project.

**Comment by fallaciousreasoning** [comment]
Wow, thanks @slawomirkolodziej! Cheers for making this library, it's really useful.
